CREATE TABLE `llm_call_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`requestId` varchar(32) NOT NULL,
	`companyId` varchar(64),
	`companyName` varchar(128),
	`userId` int,
	`phone` varchar(20),
	`feature` varchar(64) NOT NULL,
	`source` varchar(32) DEFAULT 'web',
	`modelCode` varchar(64) NOT NULL,
	`modelName` varchar(128),
	`provider` varchar(64),
	`success` int NOT NULL DEFAULT 1,
	`failReason` text,
	`httpStatus` int,
	`isSwitched` int NOT NULL DEFAULT 0,
	`originalModel` varchar(64),
	`switchTrace` json,
	`inputTokens` int NOT NULL DEFAULT 0,
	`outputTokens` int NOT NULL DEFAULT 0,
	`totalTokens` int NOT NULL DEFAULT 0,
	`inputPrice` varchar(20) DEFAULT '0',
	`outputPrice` varchar(20) DEFAULT '0',
	`estimatedCost` varchar(20) NOT NULL DEFAULT '0',
	`requestTime` timestamp NOT NULL DEFAULT (now()),
	`responseTime` timestamp,
	`durationMs` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `llm_call_logs_id` PRIMARY KEY(`id`),
	CONSTRAINT `llm_call_logs_requestId_unique` UNIQUE(`requestId`)
);
--> statement-breakpoint
CREATE TABLE `llm_models` (
	`id` int AUTO_INCREMENT NOT NULL,
	`modelCode` varchar(64) NOT NULL,
	`modelName` varchar(128) NOT NULL,
	`provider` varchar(64) NOT NULL,
	`apiUrl` varchar(512) NOT NULL,
	`apiKey` varchar(1024) NOT NULL,
	`modelType` varchar(32) NOT NULL,
	`isActive` int NOT NULL DEFAULT 1,
	`priority` int NOT NULL DEFAULT 100,
	`inputPrice` varchar(20) NOT NULL DEFAULT '0',
	`outputPrice` varchar(20) NOT NULL DEFAULT '0',
	`maxContext` int NOT NULL DEFAULT 8192,
	`maxOutput` int NOT NULL DEFAULT 4096,
	`remark` text,
	`isDeleted` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `llm_models_id` PRIMARY KEY(`id`),
	CONSTRAINT `llm_models_modelCode_unique` UNIQUE(`modelCode`)
);
